### ISSUE TITLE
Still using cl macros (and functions?)

### ISSUE THREAD

**Issue by npostavs** [emacsorphanage/yascroll#18]
See http://emacs.stackexchange.com/a/18501/5296

I notice a few `destructuring-bind` that were not converted to `cl-destructuring-bind`. Possibly there are some other missed conversions.

**Comment by jcs090218** [comment]
Does the issue still appears? `cl` is deprecated after Emacs version 27. We are requiring `cl-lib` instead right now.

**Comment by npostavs** [comment]
Looks like this was fixed in f507c884a5fd89cd02140bb53f61c814545f005e
