### ISSUE TITLE
Working with linum-mode

### ISSUE THREAD

**Issue by m2ym** [emacsorphanage/yascroll#2]
Corruption on empty lines.

**Comment by kaaresl** [comment]
Can confirm. With linum-mode enabled, the scroll-bar is indented (at least) as many positions to the left as there are digits in the line number columns. So if the screen only shows lines 0-9 (rarely relevant as you usually have more than 10 rows visible in the buffer) the scrollbar is indented 1+C positions (C = some constant). For screens with 10-99 lines the scrollbar is indented 2+C to the left, and for 100-999 3+C, and so forth.

In addition, the scrollbar is rendered wrong when it crosses lines that extends the width of the screen. (truncate or wrap lines all the same). It seems like the scrollbar has the right column position only for that exact line, the rest of the scrollbar is indented wrong.

This screen shot says it all:

![yascroll-linum-error](https://user-images.githubusercontent.com/287699/36934133-fad5093e-1ee4-11e8-8f2e-b7d32ccc4863.png)

**Comment by azzamsa** [comment]
I *think* this issue is not relevant anymore. Now we have `display-line-numbers-mode`. I tried it with yascroll, everything works fine.

**Comment by kaaresl** [comment]
I'm afraid it still is. `linum-mode` and `line-number-mode` works differently. The first adds the line numbers in the left margin, as shown on the screenshot, the second just adds the current line number on the mode line. I prefer `linum-mode` as it give a better overview where you are. `line-number-mode` forces me to look this number up, searching, scanning the screen whenever I need it (all the time).

So in my case, it's still relevant. My setup is such that I primarily work in GUI environments with emacs-client frames as the visual editor. The emacs server is running in a screen/tmux session so I can restore the very same session from all over the world.

**Comment by azzamsa** [comment]
Do you know that those modes already superseded by [display-line-numbers](https://github.com/emacs-mirror/emacs/blob/ff49d86b6419f88205ff9a5d8b1cc46fcda8371c/etc/NEWS#L493) ?

**Comment by kaaresl** [comment]
I'm so sorry, i misread your previous comment. No, I didn't know this, but it seems like excellent news and will make this issue obsolete/irrelevant, absolutely!

**Comment by azzamsa** [comment]
:). Happy hacking.

**Comment by kaaresl** [comment]
I'm sure this issue can be closed. Linum-mode actually works great now. Par with display-line-numbers-mode.

**Comment by jcs090218** [comment]
Thanks! Your contributions are very helpful to this package! :D
