### ISSUE TITLE
Nothing happens when I enable yascroll

### ISSUE THREAD

**Issue by LouisAsh** [emacsorphanage/yascroll#21]
I use Emacs 25.2.1 under Windows 10 64bits and just properly installed yascroll. However, when I enter `M-x global-yascroll-bar-mode RET` nothing changes in the scroll-bars, despite of the message saying "Yascroll-Bar Mode enabled".

When I reopen Emacs, there is still nothing like a yascroll-bar.

**Comment by azzamsa** [comment]
Have you tried changing the background and foreground color ?. It might be the same black as your current theme.

Change it via customize-mode or directly to your config.

``` elisp
(yascroll:thumb-fringe ((t (:background "#91ee98" :foreground "#91ee98"))))
```

**Comment by jcs090218** [comment]
@LouisAsh Does @azzamsa's solution resolved your issue? Thanks!

**Comment by jcs090218** [comment]
This issue is closed because of the inactivity. Please reopened this if you find out this is necessary to be discussed! Thanks!
