### ISSUE TITLE
Support display-line-numbers-mode

### ISSUE THREAD

**Issue by kaaresl** [emacsorphanage/yascroll#23]
So, as mentioned in #2, `display-line-numbers-mode` in emacs-26 supersedes linum-mode, but `display-line-numbers-mode` doesn't touch `(window-width)`. See discussion in upstream [bug#28248: 26.0.50](https://groups.google.com/d/msg/gnu.emacs.bug/pxOxaocXa2s/Gg4Z8N0QAAAJ). This causes the scroll-bar to be pushed out of the screen as the calculation in `yascroll:line-edge-position` needs to calculate the dead columns swallowed by display-line-numbers-mode. Pull request coming up.

**Comment by kaaresl** [comment]
See #24.

**Comment by jcs090218** [comment]
Thanks for opening the issue.

I know what you are talking but I don't encountered the issue above. I mean I don't see what is broken or what not. 😕 I also uses `display-line-numbers-mode` and everything works fine to me. Would you elaborate a little bit more and explain why this PR should be merged? Thanks! 😄

**Comment by kaaresl** [comment]
This bug is only present in tty emacs-26.3 (`$ emacs -nw`) in both debian and ubuntu packages. I.e. no fringe and using the 'text-area `(setq yascroll:scroll-bar 'text-area)` renderer. And it doesn't matter what packages are enabled and not. I've tried with and without my `~/.emacs` init file and no difference. The result is the same with `display-line-numbers-mode` enabled:

![Screenshot from 2020-02-19 14-51-58](https://user-images.githubusercontent.com/287699/74840512-69147600-5327-11ea-9cbe-a0861a28a463.png)

I haven't found a way to use the margin/fringe for yascroll in console emacs.

Steps to reproduce:
1. Use this as ~/.emacs
```elisp
(add-to-list 'load-path "~/src/yascroll")
(require 'yascroll)
(setq yascroll:delay-to-hide nil)
(setq yascroll:scroll-bar 'text-area)
(setq-default truncate-lines t)
```
2. Open a scrollable file: `$ emacs -nw ~/src/yascroll/yascroll.el`
3. Enable display-line-numbers-mode
4. Scroll vertically

Also, there was a bug in the previous PR. If the `display-line-numbers` package isn't loaded, testing its var would cause an error. I now instead use `(boundp 'display-line-numbers-mode)`.

**Comment by jcs090218** [comment]
Thanks for the fixed! :D Merged!
