### ISSUE TITLE
How can I change the color of the scroll bar? 

### ISSUE THREAD

**Issue by nazzacode** [emacsorphanage/yascroll#40]
This might be a noob question... but how can I change the color of the bar?

**Comment by jcs090218** [comment]
There are two faces, `yascroll:thumb-text-area` and `yascroll:thumb-fringe`. You can customize those variables!

**Comment by nazzacode** [comment]
Thankyou. For an example I have the following in my config

```elisp
(custom-set-faces!
 `(yascroll:thumb-fringe :foreground "grey" :background "grey"))
```

**Comment by jcs090218** [comment]
No problem! I'm glad you figure it out!
